apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector: 
    matchLabels: 
      mysql: ready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-lib
      volumes:
        - name: mysql-lib
          persistentVolumeClaim:
            claimName: mysql-pv-claim
