apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: admin
  password: "1234"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx:alpine
      env:
        - name: USER_TEST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD_TEST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
